export { default as Home } from './Home'
export { default as Pricing } from './Pricing'
export { default as About } from './About'
export { default as ContactUs } from './ContactUs'
export { default as Layout } from './Layout'
